name: "Reports"

on:
  push:
    branches:
      - master

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: Install dependencies
        run: |
          corepack enable
          yarn install --frozen-lockfile

      - name: Run benchmarks
        run: |
          for file in benchmarks/*.js; do
            node "${file}"
          done

      - name: Generate report
        run: ./scripts/generate-report reports/*.json

      - name: Commit report
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update report'
          add: 'REPORT.md'
